name: Readme Generator

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *  # 5 da manhã (horário de Brasília UTC-3)
    - cron: 0 20 * * * # 5 da tarde (horário de Brasília UTC-3)

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-readme-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate new README.md file
        run: bun .github/scripts/readme-generator.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN != '' && secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: |
            docs: regenerate readme app list
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: bot/readme-update
          title: |
            readme-generator: update readme
          body: |
            Automated README update with latest apps
          labels: bot
          draft: false